
export const Awards2012 = [
    {id: 1, awardtitle:"21st Century Award", awardwinner: "Spotify"},
    {id: 2,awardtitle:"Best Sync Usage", awardwinner: "Glassnote Records (GIVERS’ song “Saw You First” in Kindle Fire product launch)"},
    {id: 3,awardtitle:"Creative Packaging Award (Physical or Digital)", awardwinner: "Ninja Tune for Amon Tobin (ISAM limited edition “Control Over Nature” CD/Book)"},
    {id: 4,awardtitle:"Independent Album of the Year presented by Official.fm", awardwinner: "Bon Iver – Bon Iver (Jagjaguwar)"},
    {id: 5,awardtitle:"Indie Label of the Year Award (5 Employees or less worldwide)", awardwinner: "Daptone Records"},
    {id: 6,awardtitle:"Indie Label of the Year Award (6 Employees or more worldwide)", awardwinner: "Jagjaguwar"},
    {id: 7,awardtitle:"Lifetime Acheivement Award", awardwinner: "Martin Mills, Beggars Group Founder/CEO"},
    {id: 8,awardtitle:"Light Bulb Award (most innovative/creative marketing campaign)", awardwinner: "Epitaph/Anti- Records (Tom Waits Invite-Only Listening Party)"},
    {id: 9,awardtitle:"Music Supervisor of the Year", awardwinner: "PJ Bloom (Neophonic)"},
    {id: 10,awardtitle:"Road Warrior of the Year", awardwinner: "Charles Bradley (Daptone Records)"},
    {id: 11,awardtitle:"Up and Comer Award presented by eMusic", awardwinner: "The Dø (Six Degrees Records) [A2IM member vote] & JC Brooks and the Uptown Sound (Bloodshot Records) [eMusic member vote]"},
    {id: 12,awardtitle:"Video of the Year", awardwinner: "Arcade Fire’s “Sprawl II (Mountains Beyond Mountains)” (Merge Records)"},
]

export const Awards2013 = [
    {id: 1, awardtitle:"21st Century Award (sponsored by Caroline)", awardwinner: "Spotify"},
    {id: 2,awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Tom Silverman (Tommy Boy)"},
    {id: 3,awardtitle:"Best Live Act of the Year", awardwinner: "Alabama Shakes (ATO Records)"},
    {id: 4,awardtitle:"Best Sync Usage (sponsored by Getty Images Music)", awardwinner: "Dualtone Music Group for The Lumineers’ “Ho Hey” song placement with Bing"},
    {id: 5,awardtitle:"Creative Packaging Award (sponsored by A to Z Media)", awardwinner: "Fritz Klaetke for “Woody at 100: The Woody Guthrie Centennial Collection” – Woody Guthrie (Smithsonian Folkways)"},
    {id: 6,awardtitle:"Independent Album of the Year (sponsored by Spotify)", awardwinner: "‘Boys & Girls’ by Alabama Shakes (ATO Records)"},
    {id: 7,awardtitle:"Independent Label of the Year Award Big (sponsored by ADA)", awardwinner: "Glassnote Records"},
    {id: 8,awardtitle:"Independent Label of the Year Award Small (sponsored by The Orchard)", awardwinner: "Dualtone Music Group"},
    {id: 9,awardtitle:"Light Bulb Award", awardwinner: "Glassnote Records, Gentlemen Of The Road, and Mumford & Sons for the ‘Stopover’ tour for Babel"},
    {id: 10,awardtitle:"Music Supervisor of the Year (sponsored by Silva Screen Music Group)", awardwinner: "Alexandra Patsavas (Chop Shop Music)"},
    {id: 11,awardtitle:"Road Warrior - Hardest Working Artist of the Year (sponsored by Believe Digital)", awardwinner: "The Lumineers (Dualtone Music Group)"},
    {id: 12,awardtitle:"Up and Comer Award – A2IM Member Vote (sponsored by eMusic)", awardwinner: "Mikal Cronin (Merge Records)"},
    {id: 13,awardtitle:"Up and Comer Award – eMusic Fan Vote (sponsored by eMusic)", awardwinner: "The Virginmarys (Wind-up Records)"},
    {id: 14,awardtitle:"Video of the Year", awardwinner: "“Thrift Shop” by Macklemore & Ryan Lewis (Macklemore, LLC)"},
]

export const Awards2014 = [
    {id: 1, awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Bruce Iglauer (Alligator Records)"},
    {id: 2,awardtitle:"Best Live Act of the Year (sponsored by Entertainment One)", awardwinner: "Arcade Fire 'Reflektor' (Merge Records)"},
    {id: 3,awardtitle:"Best Sync Usage (sponsored by Silva Screen Music)", awardwinner: "Alabama Shakes 'You Ain't Alone' (ATO Records) in Dallas Buyers Club (by District Music)"},
    {id: 4,awardtitle:"Breakthrough Artist of the Year (sponsored by INgrooves)", awardwinner: "Chvrches 'The Bones of What You Believe' (Glassnote)"},
    {id: 5,awardtitle:"Creative Packaging Award (sponsored by A to Z Media)", awardwinner: "Kurt Vile 'Wakin On A Pretty Daze Deluxe LP' (Matador Records) by Stephen Powers/ESPO"},
    {id: 6,awardtitle:"Hardest Working Artist", awardwinner: "Charles Bradley (Daptone Records)"},
    {id: 7,awardtitle:"Independent Album of the Year (sponsored by Spotify)", awardwinner: "Arcade Fire 'Reflektor' (Merge Records) & Arctic Monkeys 'AM' (Domino Recordings)"},
    {id: 8,awardtitle:"Independent Ally of the Year (sponsored by Caroline)", awardwinner: "NPR Music"},
    {id: 9,awardtitle:"Independent Label of the Year Award (sponsored by ADA)", awardwinner: "Glassnote Records"},
    {id: 10,awardtitle:"Independent Label of the Year Award (sponsored by The Orchard)", awardwinner: "Daptone Records"},
    {id: 11,awardtitle:"Light Bulb Award (sponsored by Redeye)", awardwinner: "Steven Hill & Josh Berman (Warp Records), Boards of Canada - Tomorrow's Harvest"},
    {id: 12,awardtitle:"Up and Comer Award - A2IM Member Vote (sponsored by Beats Music)", awardwinner: "Angel Olsen 'Burn Your Fire For No Witness' (Jagjaguwar)"},
    {id: 13,awardtitle:"Video of the Year (sponsored by Merlin)", awardwinner: "Arcade Fire 'Reflektor' (Merge Records)"},
]

export const Awards2015 = [
    {id: 1,awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Pat Chin and the Chin Family (VP Records) Founder/Founding Family"},
    {id: 2,awardtitle:"Album of the Year (sponsored by Fox Rothschild LLP)", awardwinner: "The War on Drugs 'Lost In the Dream' (Secretly Canadian)"},
    {id: 3,awardtitle:"Best Sync Usage (sponsored by Silva Screen/So Recordings)", awardwinner: "Family of the Year 'Hero' (usage: 'Boyhood') (Nettwerk)"},
    {id: 4,awardtitle:"Breakthrough Artist of the Year (Sponsored by Merlin)", awardwinner: "Sturgill Simpson (High Top Mountain/Thirty Tigers)"},
    {id: 5,awardtitle:"Creative Packaging Award (sponsored by A to Z Media)", awardwinner: "Aphex Twin 'Syro' (Warp)"},
    {id: 6,awardtitle:"Groundbreaking Album of the Year (sponsored by INgrooves)", awardwinner: "Run the Jewels 'Run the Jewels 2' (Mass Appeal)"},
    {id: 7,awardtitle:"Hardest Working Artist of the Year (sponsored by BMI)", awardwinner: "Sharon Jones & The Dap-Kings (Daptone)"},
    {id: 8,awardtitle:"Heritage Album of the Year", awardwinner: "Sturgill Simpson 'Metamodern Sounds in Country Music' (High Top Mountain/Thirty Tigers)"},
    {id: 9,awardtitle:"Independent Champion", awardwinner: "Merlin"},
    {id: 10,awardtitle:"Label of the Year (5 or Less Employees) (sponsored by The Orchard)", awardwinner: "Ghostly International"},
    {id: 11,awardtitle:"Label of the Year (6 or More Employees) (sponsored by ADA)", awardwinner: "Sub Pop"},
    {id: 12,awardtitle:"Marketing Genius Award", awardwinner: "Run the Jewels 'Meow the Jewels / Tag the Jewels' (marketing lead: Run the Jewels) (Mass Appeal)"},
    {id: 13,awardtitle:"Marketplace Ally", awardwinner: "Record Store Day"},
    {id: 14,awardtitle:"Video of the Year - Fan Vote (sponsored by YouTube)", awardwinner: "Die Antwoord 'Ugly Boy' (Zef Records/Kobalt Label Services)"},
    {id: 15,awardtitle:"Video of the Year (sponsored by YouTube)", awardwinner: "FKA Twigs 'Two Weeks' (Young Turks)"},
]

export const Awards2016 = [
    {id: 1, awardtitle:"A&R Team of the Year", awardwinner: "ATO Records"},
    {id: 2, awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Mike Curb - Founder (Curb Records)"},
    {id: 3, awardtitle:"Album of the Year (Sponsored by Spotify)", awardwinner: "Alabama Shakes - Sound & Color | ATO Records"},
    {id: 4, awardtitle:"Best Live Act (Sponsored by Kickstarter)", awardwinner: "Alabama Shakes | ATO Records"},
    {id: 5, awardtitle:"Best Sync Usage (Sponsored by Silva Screen Music / So Recordings / SBMC Inc.)", awardwinner: "Alabama Shakes - Apple iPad Pro (Music Supervisor: Jimmy Dickson) | ATO Records"},
    {id: 6, awardtitle:"Breakthrough Artist (Sponsored by Fox Rothschild)", awardwinner: "Courtney Barnett - Sometimes I Sit and Think, and Sometimes I Just Sit | Mom+Pop"},
    {id: 7, awardtitle:"Creative Packaging (Sponsored by AtoZ Media)", awardwinner: "Father John Misty - I Love You Honeybear (Creative Director: Sasha Barr) | Sub Pop Records"},
    {id: 8, awardtitle:"Groundbreaking Album of the Year (Sponsored by Ingrooves)", awardwinner: "Kamasi Washington - The Epic | Brainfeeder"},
    {id: 9, awardtitle:"Heritage Album of the Year", awardwinner: "Kamasi Washington - The Epic | Brainfeeder"},
    {id: 10, awardtitle:"Independent Champion (Sponsored by FUGA)", awardwinner: "Merlin"},
    {id: 11, awardtitle:"Into the Pit", awardwinner: "Savages - Adore Life | Matador Records"},
    {id: 12, awardtitle:"Label of the Year (Medium) (Sponsored by ADA)", awardwinner: "Sub Pop Records"},
    {id: 13, awardtitle:"Label of the Year (Small) (Sponsored by The Orchard)", awardwinner: "Daptone Records"},
    {id: 14, awardtitle:"Marketing Genius (Sponsored by Caroline)", awardwinner: "Run The Jewels - #12DaysofRTJ - (Marketing Lead:Amaechi Uzoigwe, Zena White & Amit Nerurkar) | Mass Appeal Records"},
    {id: 15, awardtitle:"Shifting Beats Award (Sponsored by IDOL)", awardwinner: "Jamie xx - In Colour | Young Turks"},
    {id: 16, awardtitle:"Video of the Year - Fan Vote", awardwinner: "Grimes - Kill V. Maim | 4AD"},
    {id: 17, awardtitle:"Video of the Year (Sponsored by YouTube/Google Play)", awardwinner: "Run The Jewels - Close Your Eyes (and Count to F*ck) | Mass Appeal Records"},
]

export const Awards2017 = [
    {id: 1, awardtitle:"A2IM Impact Award (Powered by Nielsen Music)", awardwinner: "Florida Georgia Line - Dig Your Roots | Big Machine Label Group"},
    {id: 2, awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Ani DiFranco | Righteous Babe Records"},
    {id: 3, awardtitle:"Album of the Year (Sponsored by The Orchard)", awardwinner: "Angel Olsen - My Woman | Jagjaguwar"},
    {id: 4, awardtitle:"Best Blues/Jazz/R&B Album", awardwinner: "Charles Bradley - Changes | Daptone Records"},
    {id: 5, awardtitle:"Best Classical/World Album", awardwinner: "Tinariwen - Elwan | Anti-"},
    {id: 6, awardtitle:"Best Country/Americana/Folk Album", awardwinner: "Margo Price - Midwest Farmers Daughter | Third Man Records"},
    {id: 7, awardtitle:"Best Dance/Electronica Album (Sponsored by FUGA)", awardwinner: "Bonobo - Migration | Ninja Tune"},
    {id: 8, awardtitle:"Best Live Act (Sponsored by Kickstarter)", awardwinner: "Radiohead (XL Recordings)"},
    {id: 9, awardtitle:"Best Metal/Hard Rock Album (Sponsored by Fox Rothschild)", awardwinner: "King Gizzard & The Lizard Wizard - Nonagon Infinity | ATO Records"},
    {id: 10, awardtitle:"Best Rap/Hip-Hop Album", awardwinner: "Run The Jewels - Run the Jewels 3 | Run the Jewels, Inc."},
    {id: 11, awardtitle:"Best Sync Usage (Sponsored by DISCO)", awardwinner: "Sharon Jones & The Dap-Kings - Lincoln MKZ Spot | Daptone Records"},
    {id: 12, awardtitle:"Breakthrough Artist (Sponsored by INgrooves)", awardwinner: "Whitney - Light Upon the Lake | Secretly Canadian"},
    {id: 13, awardtitle:"Creative Packaging", awardwinner: "Thundercat - Drunk | Brainfeeder"},
    {id: 14, awardtitle:"Independent Champion", awardwinner: "Bandcamp"},
    {id: 15, awardtitle:"Independent Icon", awardwinner: "Nick Lowe"},
    {id: 16, awardtitle:"Label of the Year (Medium) (Sponsored by ADA)", awardwinner: "Jagjaguwar"},
    {id: 17, awardtitle:"Label of the Year (Small) (Sponsored by Spotify)", awardwinner: "Triple Crown Records"},
    {id: 18, awardtitle:"Marketing Genius (Sponsored by Caroline)", awardwinner: "The xx - I See You | Young Turks"},
    {id: 19, awardtitle:"Video of the Year - Fan Vote (Sponsored by YouTube/Google Play)", awardwinner: "Radiohead - Daydreaming | XL Recordings"},
    {id: 20, awardtitle:"Video of the Year (Sponsored by YouTube/Google Play)", awardwinner: "DJ Shadow feat. Run The Jewels - Nobody Speak | Mass Appeal Records"},
]

export const Awards2018 = [
    {id: 1, awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Brett Gurewitz - Founder (Epitaph/Anti-)"},
    {id: 2, awardtitle:"Album of the Year (Presented By The Orchard)", awardwinner: "Slowdive - Slowdive (Dead Oceans)"},
    {id: 3, awardtitle:"Best American Roots & Folk Album", awardwinner: "Aimee Mann - Mental Illness (SuperEgo Records)"},
    {id: 4, awardtitle:"Best Blues Album", awardwinner: "Benjamin Booker - Witness (ATO Records)"},
    {id: 5, awardtitle:"Best Classical Album", awardwinner: "Detroit Symphony Orchestra; Leonard Slatkin (conductor) - Copland: Symphony No. 3 & 3 Latin American Sketches (Naxos)"},
    {id: 6, awardtitle:"Best Country/Americana Album", awardwinner: "Jason Isbell and the 400 Unit - The Nashville Sound (Southeastern Records/Thirty Tigers)"},
    {id: 7, awardtitle:"Best Dance/Electronic Album (Presented by Symphonic Distribution)", awardwinner: "Sylvan Esso - What Now (Loma Vista Recordings)"},
    {id: 8, awardtitle:"Best Hip-Hop/Rap Album (Presented by Fox Rothschild LLP)", awardwinner: "Shabazz Palaces - Quazarz: Born on a Gangster Star (Sub Pop Records)"},
    {id: 9, awardtitle:"Best Jazz Album", awardwinner: "Kamasi Washington - Harmony of Difference (Young Turks)"},
    {id: 10, awardtitle:"Best Latin Album", awardwinner: "Chicano Batman - Freedom Is Free | ATO Records"},
    {id: 11, awardtitle:"Best Live Act", awardwinner: "Nick Cave & The Bad Seeds | Bad Seed LTD"},
    {id: 12, awardtitle:"Best Metal Album (Presented by Mitchell Silberberg & Knupp LLP)", awardwinner: "Converge - The Dusk In Us | Epitaph Records"},
    {id: 13, awardtitle:"Best Outlier Album (Presented by Songtrust)", awardwinner: "Moses Sumney - Aromanticism | Jagjaguwar"},
    {id: 14, awardtitle:"Best R&B Album", awardwinner: "Sharon Jones & The Dap-Kings - Soul of a Woman (Daptone Records)"},
    {id: 15, awardtitle:"Best Re-Issue", awardwinner: "Elliott Smith - Either/Or: Expanded Edition (Kill Rock Stars)"},
    {id: 16, awardtitle:"Best Rock Album", awardwinner: "The National - Sleep Well Beast (4AD)"},
    {id: 17, awardtitle:"Best Sync Usage (Presented By DISCO)", awardwinner: "Cigarettes After Sex - The Handmaid's Tale on Hulu (Music Supervision: Jessica Dolinger) (Partisan Records / Spanish Prayers)"},
    {id: 18, awardtitle:"Best World Album", awardwinner: "Ibeyi - Ash | XL Recordings"},
    {id: 19, awardtitle:"Breakthrough Artist (Presented By INgrooves)", awardwinner: "Princess Nokia - 1992 Deluxe | Rough Trade Records"},
    {id: 20, awardtitle:"Creative Packaging", awardwinner: "Bob’s Burgers - The Bob’s Burgers Music Album | Sub Pop Records"},
    {id: 21, awardtitle:"Independent Champion", awardwinner: "Merlin"},
    {id: 22, awardtitle:"Label of the Year (Big) (Presented By ADA)", awardwinner: "Dead Oceans"},
    {id: 23, awardtitle:"Label of the Year (Small) (Presented By Spotify)", awardwinner: "Daptone Records"},
    {id: 24, awardtitle:"Marketing Genius", awardwinner: "Run the Jewels - Call Ticketron! - 646.846.RTJ3 (www.1215.runthejewels.com) (Marketing Lead: Amaechi Uzoigwe & Lee Martin) | Run the Jewels, Inc."},
    {id: 25, awardtitle:"Video of the Year", awardwinner: "Perfume Genius - Die 4 You (Matador Records)"},
]

export const Awards2019 = [
    {id: 1, awardtitle:"A2IM Lifetime Achievement Award", awardwinner: "Jonathan Poneman (Sub Pop Records)"},
    {id: 2, awardtitle:"Album of the Year", awardwinner: "Kamasi Washington - Heaven and Earth (Young Turks)"},
    {id: 3, awardtitle:"Best American Roots/Folk Album", awardwinner: "John Prine - The Tree of Forgiveness (Oh Boy Records)"},
    {id: 4, awardtitle:"Best Blues Album", awardwinner: "Fantastic Negrito - Please Don't Be Dead (Cooking Vinyl)"},
    {id: 5, awardtitle:"Best Classical Album", awardwinner: "Jean-Michel Blais - Dans Ma Main (Arts & Crafts Productions Inc.)"},
    {id: 6, awardtitle:"Best Country/Americana Album", awardwinner: "John Prine - The Tree of Forgiveness (Oh Boy Records)"},
    {id: 7, awardtitle:"Best Dance/Electronic Album", awardwinner: "Yves Tumor - Safe In The Hands Of Love (Warp Records)"},
    {id: 8, awardtitle:"Best Hip-Hop/Rap Album", awardwinner: "Awkwafina - In Fina We Trust (Awkwafina Records / AWAL)"},
    {id: 9, awardtitle:"Best Jazz Album", awardwinner: "Kamasi Washington - Heaven and Earth (Young Turks)"},
    {id: 10, awardtitle:"Best Latin Album", awardwinner: "Bad Bunny - X 100PRE (Rimas Entertainment)"},
    {id: 11, awardtitle:"Best Live Act", awardwinner: "BADBADNOTGOOD (Innovative Leisure)"},
    {id: 12, awardtitle:"Best Metal Album", awardwinner: "Deafheaven - Ordinary Corrupt Human Love (ANTI- Records)"},
    {id: 13, awardtitle:"Best Outlier Album", awardwinner: "Khruangbin - Con Todo El Mundo (Dead Oceans)"},
    {id: 14, awardtitle:"Best R&B Album", awardwinner: "Charles Bradley - Black Velvet (Daptone Records)"},
    {id: 15, awardtitle:"Best Re-Issue", awardwinner: "Pixies - Come On Pilgrim...It's Surfer Rosa (4AD)"},
    {id: 16, awardtitle:"Best Rock Album", awardwinner: "Courtney Barnett - Tell Me How You Really Feel (Mom+Pop)"},
    {id: 17, awardtitle:"Best Sync Usage", awardwinner: "Run the Jewels, Black Panther (RTJ Music, Inc.)"},
    {id: 18, awardtitle:"Best World Album", awardwinner: "Bombino - Deran (Partisan Records)"},
    {id: 19, awardtitle:"Breakthrough Artist", awardwinner: "IDLES - Joy as an Act of Resistance (Partisan Records)"},
    {id: 20, awardtitle:"Creative Packaging", awardwinner: "Kamasi Washington - Heaven and Earth (Young Turks)"},
    {id: 21, awardtitle:"Independent Champion", awardwinner: "NPR"},
    {id: 22, awardtitle:"Label of the Year (Big)", awardwinner: "Domino Recording Co. Ltd."},
    {id: 23, awardtitle:"Label of the Year (Medium)", awardwinner: "Partisan Records"},
    {id: 24, awardtitle:"Label of the Year (Small)", awardwinner: "Daptone Records"},
    {id: 25, awardtitle:"Marketing Genius Award", awardwinner: "Aphex Twin - Collapse EP (Warp Records)"},
    {id: 26, awardtitle:"Video of the Year", awardwinner: "Mitski - Nobody (Dead Oceans)"},
]

export const Awards2020 = [
    {id: 1, awardtitle:"Album of the Year (sponsored by The Orchard)", awardwinner: "Big Thief - U.F.O.F (4AD)"},
    {id: 2, awardtitle:"Best Alternative Rock Album", awardwinner: "Fontaines D.C. - Dogrel (Partisan Records)"},
    {id: 3, awardtitle:"Best Americana Album", awardwinner: "Steve Gunn - The Unseen In Between (Matador Records)"},
    {id: 4, awardtitle:"Best Blues Album", awardwinner: "Mavis Staples - We Get By (Anti Records)"},
    {id: 5, awardtitle:"Best Classical Album", awardwinner: "Beth Gibbons - Henryk Gorecki: Symphony No. 3 (Symphony Of Sorrowful Songs) (Domino)"},
    {id: 6, awardtitle:"Best Country Album", awardwinner: "Orville Peck - Pony (Sub Pop Records)"},
    {id: 7, awardtitle:"Best Dance/Electronic Album", awardwinner: "Flying Lotus - Flamagra (Warp Records)"},
    {id: 8, awardtitle:"Best Folk/Bluegrass Album", awardwinner: "Julia Jacklin - Crushing (Polyvinyl Record Co.)"},
    {id: 9, awardtitle:"Best Hip-Hop/Rap Album", awardwinner: "Danny Brown - uknowhatimsayin¿ (Warp Records)"},
    {id: 10, awardtitle:"Best Indie Rock Album", awardwinner: "Weyes Blood - Titanic Rising (Sub Pop Records)"},
    {id: 11, awardtitle:"Best Jazz Album (sponsored by Qobuz)", awardwinner: "Nerija - Blume (Domino)"},
    {id: 12, awardtitle:"Best Latin Album", awardwinner: "Y La Bamba - Mujeres (Tender Loving Empire Records)"},
    {id: 13, awardtitle:"Best Live Act", awardwinner: "IDLES (Partisan Records)"},
    {id: 14, awardtitle:"Best Mainstream Rock Album", awardwinner: "Cigarettes After Sex - Cry (Partisan Records)"},
    {id: 15, awardtitle:"Best Metal Album", awardwinner: "King Gizzard & The Lizard Wizard - Infest The Rats' Nest (ATO Records)"},
    {id: 16, awardtitle:"Best Outlier Album (Sponsored by Amazon Music)", awardwinner: "Cate Le Bon - Reward (Mexican Summer)"},
    {id: 17, awardtitle:"Best Punk/Emo Album", awardwinner: "Amyl and The Sniffers - Amyl and The Sniffers (ATO Records)"},
    {id: 18, awardtitle:"Best R&B Album", awardwinner: "Sudan Archives - Athena (Stones Throw Records)"},
    {id: 19, awardtitle:"Best Re-Issue", awardwinner: "Stereolab - Reissues (Warp Records)"},
    {id: 20, awardtitle:"Best Sync Usage", awardwinner: "IDLES - Peaky Blinders (Partisan Records)"},
    {id: 21, awardtitle:"Best World Album", awardwinner: "Tinariwen - Amadjar (Anti Records)"},
    {id: 22, awardtitle:"Breakthrough Artist/Release (sponsored by Ingrooves)", awardwinner: "Orville Peck (Sub Pop Records)"},
    {id: 23, awardtitle:"Creative Packaging", awardwinner: "Flying Lotus - Flamagra (Warp Records)"},
    {id: 24, awardtitle:"Independent Champion (sponsored by Merlin)", awardwinner: "Bandcamp"},
    {id: 25, awardtitle:"Label of the Year (Big) (sponsored by ADA)", awardwinner: "Partisan Records"},
    {id: 26, awardtitle:"Label of the Year (Medium)", awardwinner: "Sacred Bones"},
    {id: 27, awardtitle:"Label of the Year (Small) (sponsored by Spotify)", awardwinner: "Father / Daughter Records"},
    {id: 28, awardtitle:"Marketing Genius", awardwinner: "Megan Thee Stallion - Hot Girl Summer (300 Entertainment)"},
    {id: 29, awardtitle:"Video of the Year (sponsored by YouTube Music)", awardwinner: "FKA twigs - “Cellophane” (Young Turks)"},
]

export const Awards2021 = [
    {id: 1, awardtitle:"A2IM HUMANITARIAN AWARD", awardwinner: "Killer Mike & EL-P of Run the Jewels (Jewel Runners, Inc)"},
    {id: 2,awardtitle:"BEST ALTERNATIVE ROCK RECORD", awardwinner: "Phoebe Bridgers - Punisher (Dead Oceans)"},
    {id: 3,awardtitle:"BEST AMERICANA RECORD", awardwinner: "Bonny Light Horseman - Bonny Light Horseman (37d03d)"},
    {id: 4,awardtitle:"BEST BLUES RECORD", awardwinner: "Fantastic Negrito - Have You Lost Your Mind Yet? (Cooking Vinyl Ltd.)"},
    {id: 5,awardtitle:"BEST CLASSICAL RECORD", awardwinner: "Erik Hall - Music for 18 Musicians (Steve Reich) (Western Vinyl)"},
    {id: 6,awardtitle:"BEST COUNTRY RECORD", awardwinner: "Waxahatchee - Saint Cloud (Merge Records)"},
    {id: 7,awardtitle:"BEST DANCE/ELECTRONIC RECORD", awardwinner: "Caribou - Suddenly (Merge Records)"},
    {id: 8,awardtitle:"BEST FOLK/BLUEGRASS RECORD", awardwinner: "Angel Olsen- Whole New Mess (Jagjaguwar)"},
    {id: 9,awardtitle:"BEST HIP-HOP/RAP RECORD Presented by Virgin Music", awardwinner: "Run the Jewels - RTJ4 (Jewel Runners, Inc.)"},
    {id: 10,awardtitle:"BEST JAZZ RECORD Presented by Qobuz", awardwinner: "Gil-Scott Heron & Makaya McCraven - We're New Again - A Reimagining by Makaya McCraven (XL Recordings)"},
    {id: 11,awardtitle:"BEST LATIN RECORD", awardwinner: "Gabriel Garzón-Montano - Agüita (Jagjaguwar in partnership with Stones Throw Records)"},
    {id: 12,awardtitle:"BEST LIVE/LIVESTREAM ACT", awardwinner: "Phoebe Bridgers (Dead Oceans)"},
    {id: 13,awardtitle:"BEST METAL RECORD", awardwinner: "Architects - “Animals” (Epitaph Records)"},
    {id: 14,awardtitle:"BEST OUTLIER RECORD Presented by The Orchard", awardwinner: "Khruangbin - Mordechai (Dead Oceans)"},
    {id: 15,awardtitle:"BEST PUNK RECORD", awardwinner: "IDLES - Ultra Mono (Partisan Records)"},
    {id: 16,awardtitle:"BEST R&B RECORD", awardwinner: "Thundercat - It Is What It Is (Brainfeeder)"},
    {id: 17,awardtitle:"BEST RE-ISSUE RECORD", awardwinner: "J Dilla - Donuts (Jelly Edition) (Stones Throw Records)"},
    {id: 18,awardtitle:"BEST ROCK RECORD Presented by MSK (Mitchell; Silberberg & Knupp, LLP)", awardwinner: "Fontaines D.C. - A Hero's Death (Partisan Records)"},
    {id: 19,awardtitle:"BEST SPIRITUAL RECORD", awardwinner: "Sun Ra Arkestra - Swirling (STRUT)"},
    {id: 20,awardtitle:"BEST SYNC USAGE", awardwinner: "Run the Jewels (Jewel Runners, Inc.) - 'Ooh LA LA' - Season three of Netflix’s Ozark"},
    {id: 21,awardtitle:"BEST WORLD RECORD Presented by Redeye Worldwide", awardwinner: "Altin Gün - Ordunun Dereleri (ATO Records) & ☆ Songhoy Blues - Optimisme (Fat Possum Records)"},
    {id: 22,awardtitle:"BREAKTHROUGH ARTIST/RELEASE Presented by Ingrooves", awardwinner: "Arlo Parks (Transgressive Records)"},
    {id: 23,awardtitle:"CREATIVE PACKAGING", awardwinner: "Soccer Mommy - Color Theory limited edition back to school binder (Loma Vista Recordings)"},
    {id: 24,awardtitle:"INDEPENDENT CHAMPION Presented by Merlin", awardwinner: "Bandcamp"},
    {id: 25,awardtitle:"LABEL OF THE YEAR (BIG) Presented by ADA", awardwinner: "Sub Pop Records"},
    {id: 26,awardtitle:"LABEL OF THE YEAR (MEDIUM)", awardwinner: "Light in the Attic Records"},
    {id: 27,awardtitle:"LABEL OF THE YEAR (SMALL) Presented by Spotify", awardwinner: "Daptone Records"},
    {id: 28,awardtitle:"MARKETING GENIUS", awardwinner: "Beggars Group - Supporting Indie Retail #loverecordstores Campaign"},
    {id: 29,awardtitle:"RECORD OF THE YEAR Presented by Amazon Music", awardwinner: "Phoebe Bridgers - Punisher (Dead Oceans)"},
    {id: 30,awardtitle:"VIDEO OF THE YEAR Presented by YouTube Music", awardwinner: "FKA twigs - “Sad Day” (Young)"},
]

export const Awards2022 = [
    {id: 1, awardtitle:"Best Blues Record", awardwinner: "Christone 'Kingfish' Ingram - 662 (Alligator Records)"},
    {id: 2, awardtitle:"Best Blues Record", awardwinner: "Cedric Burnside - I Be Trying (Single Lock Records)"},
    {id: 3, awardtitle:"Best Folk/Bluegrass Record", awardwinner: "Hand Habits - Fun House (Saddle Creek)"},
    {id: 4, awardtitle:"Best Folk/Bluegrass Record", awardwinner: "Jose Gonzalez - Local Valley (Mute Records)"},
    {id: 5, awardtitle:"A2IM Humanitarian Award", awardwinner: "Common"},
    {id: 6, awardtitle:"Best Alternative Rock Record", awardwinner: "Japanese Breakfast - Jubilee (Dead Oceans)"},
    {id: 7, awardtitle:"Best Americana Record", awardwinner: "Madi Diaz - History Of A Feeling (ANTI-)"},
    {id: 8, awardtitle:"Best Classical Record", awardwinner: "Bryce Dessner, Australian String Quartet, Sydney Dance Company - Impermanence/Disintegration (37d03d)"},
    {id: 9, awardtitle:"Best Country Record", awardwinner: "Sturgill Simpson - The Ballad of Dood & Juanita (High Top Mountain Records / Thirty Tigers)"},
    {id: 10, awardtitle:"Best Dance Record", awardwinner: "Jungle - Loving In Stereo (AWAL)"},
    {id: 11, awardtitle:"Best Electronic Record", awardwinner: "박혜진 Park Hye Jin - Before I Die (Ninja Tune)"},
    {id: 12, awardtitle:"Best Heavy Record", awardwinner: "Deafheaven - Infinite Granite (Sargent House)"},
    {id: 13, awardtitle:"Best Hip-Hop/Rap Record", awardwinner: "Little Simz - Sometimes I Might Be Introvert (AWAL)"},
    {id: 14, awardtitle:"Best Jazz Record", awardwinner: "BADBADNOTGOOD - Talk Memory (XL Recordings)"},
    {id: 15, awardtitle:"Best Latin Record", awardwinner: "Helado Negro - Far In (4AD)"},
    {id: 16, awardtitle:"Best Live/Livestream Act", awardwinner: "Mdou Moctar - 'Live at the Niger River'"},
    {id: 17, awardtitle:"Best Outlier Record", awardwinner: "L'Rain - Fatigue (Mexican Summer)"},
    {id: 18, awardtitle:"Best Pop Record", awardwinner: "Arlo Parks - Collapsed In Sunbeams (Transgressive/[PIAS])"},
    {id: 19, awardtitle:"Best Punk Record", awardwinner: "The Linda Lindas - “Racist, Sexist Boy” (Live at LA Public Library) (Epitaph)"},
    {id: 20, awardtitle:"Best R&B Record", awardwinner: "Hiatus Kaiyote - Mood Valiant (Brainfeeder (Ninja Tune))"},
    {id: 21, awardtitle:"Best Re-Issue", awardwinner: "Radiohead - Kid A Mnesia (XL Recordings)"},
    {id: 22, awardtitle:"Best Rock Record", awardwinner: "IDLES - CRAWLER (Partisan Records)"},
    {id: 23, awardtitle:"Best Spiritual Record", awardwinner: "Blind Boys of Alabama feat. Bela Fleck - 'I Wish I Knew How It Would Feel To Be Free' (Single Lock Records)"},
    {id: 24, awardtitle:"Best Sync Usage", awardwinner: "Phoebe Bridgers - “I Know The End” - Ep 106 Mare of Easttown (Dead Oceans)"},
    {id: 25, awardtitle:"Best World Record", awardwinner: "Mdou Moctar - Afrique Victime (Matador Records)"},
    {id: 26, awardtitle:"Breakthrough Artist/Release", awardwinner: "Wet Leg - Chaise Longue (Domino)"},
    {id: 27, awardtitle:"Creative Packaging", awardwinner: "Japanese Breakfast - Jubilee (Dead Oceans)"},
    {id: 28, awardtitle:"Independent Champion", awardwinner: "Bandcamp"},
    {id: 29, awardtitle:"Label of the Year (Medium)", awardwinner: "Sacred Bones Records"},
    {id: 30, awardtitle:"Label of the Year (Small)", awardwinner: "Oh Boy Records"},
    {id: 31, awardtitle:"Marketing Genius", awardwinner: "Japanese Breakfast - Jubilee (Dead Oceans)"},
    {id: 32, awardtitle:"Record of the Year", awardwinner: "Japanese Breakfast - Jubilee (Dead Oceans)"},
    {id: 33, awardtitle:"Self-Released Record of the Year", awardwinner: "Cautious Clay - Deadpan Love (Cautious Clay)"},
    {id: 34, awardtitle:"Video of the Year", awardwinner: "Wet Leg - 'Chaise Longue' (Domino Recording Co.)"},
]
